"""empty message

<<<<<<<< HEAD:migrations/versions/b67d4fc73b1c_.py
Revision ID: b67d4fc73b1c
Revises: 
Create Date: 2024-03-04 19:42:39.584867
========
<<<<<<<< HEAD:migrations/versions/a0a928fa4b7d_.py
Revision ID: a0a928fa4b7d
Revises: 
Create Date: 2024-03-04 20:50:31.233930
========
Revision ID: 8c29b3a6ec1a
Revises: 
Create Date: 2024-03-04 19:42:35.160197
>>>>>>>> refs/remotes/origin/Karen:migrations/versions/8c29b3a6ec1a_.py
>>>>>>>> develop:migrations/versions/8c29b3a6ec1a_.py

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
<<<<<<<< HEAD:migrations/versions/b67d4fc73b1c_.py
revision = 'b67d4fc73b1c'
========
<<<<<<<< HEAD:migrations/versions/a0a928fa4b7d_.py
revision = 'a0a928fa4b7d'
========
revision = '8c29b3a6ec1a'
>>>>>>>> refs/remotes/origin/Karen:migrations/versions/8c29b3a6ec1a_.py
>>>>>>>> develop:migrations/versions/8c29b3a6ec1a_.py
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('user_name', sa.String(length=80), nullable=False),
    sa.Column('last_name', sa.String(length=80), nullable=False),
    sa.Column('profile_img', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('favorite_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('pet', sa.Enum('Yes', 'No', name='petchoice'), nullable=False),
    sa.Column('gender', sa.Enum('Male', 'Female', name='genderchoices'), nullable=False),
    sa.Column('budget', sa.Integer(), nullable=False),
    sa.Column('find_roomie', sa.Enum('Apartment', 'NoApartment', name='findroomiechoice'), nullable=False),
    sa.Column('text_box', sa.Text(), nullable=False),
    sa.Column('profile_img', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_properties')
    op.drop_table('favorite_profile')
    op.drop_table('user')
    # ### end Alembic commands ###
