"""empty message

Revision ID: f04bc6ff0e53
Revises: 54ed6c6a8bbc
Create Date: 2024-03-08 20:08:19.604977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f04bc6ff0e53'
down_revision = '54ed6c6a8bbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_properties', schema=None) as batch_op:
        batch_op.alter_column('profile_img',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=1000),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_properties', schema=None) as batch_op:
        batch_op.alter_column('profile_img',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###
